### ISSUE TITLE
pip install fails on Ubuntu 20.04 "ImportError: libffi.so.6: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1200]
**Describe the bug**

Upgraded Ubuntu from 18.04 to 20.04, can't install arbor anymore.

**To Reproduce**
```
robin@robin-ZenBook-UX533FN:~/workspace/arbor$ pyenv local arbor 
(arbor) robin@robin-ZenBook-UX533FN:~/workspace/arbor$ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.2.4
(arbor) robin@robin-ZenBook-UX533FN:~/workspace/arbor$ pip install arbor
Collecting arbor
  Downloading arbor-0.4.tar.gz (2.0 MB)
     |████████████████████████████████| 2.0 MB 646 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/robin/.pyenv/versions/3.8.1/envs/arbor/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-59g8cpsr/arbor/setup.py'"'"'; __file__='"'"'/tmp/pip-install-59g8cpsr/arbor/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d8a82wg9
         cwd: /tmp/pip-install-59g8cpsr/arbor/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/robin/.pyenv/versions/3.8.1/envs/arbor/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/robin/.pyenv/versions/3.8.1/envs/arbor/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/home/robin/.pyenv/versions/3.8.1/envs/arbor/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The problem is most likely that I have libffi7 and not 6 installed?

```
(arbor) robin@robin-ZenBook-UX533FN:~/workspace/arbor$ sudo apt-get install libffi7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi7 is already the newest version (3.3-4).
libffi7 set to manually installed.
The following packages were automatically installed and are no longer required:
  libcrystalhd3 linux-generic linux-generic-hwe-18.04 linux-headers-5.4.0-48 linux-headers-5.4.0-48-generic linux-image-5.4.0-48-generic linux-modules-5.4.0-48-generic
  linux-modules-extra-5.4.0-48-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(arbor) robin@robin-ZenBook-UX533FN:~/workspace/arbor$ sudo apt-get install libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.3-4).
The following packages were automatically installed and are no longer required:
  libcrystalhd3 linux-generic linux-generic-hwe-18.04 linux-headers-5.4.0-48 linux-headers-5.4.0-48-generic linux-image-5.4.0-48-generic linux-modules-5.4.0-48-generic
  linux-modules-extra-5.4.0-48-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Arbor 0.4/0.3, Python 3.8.1, libffi7

**Comment by Helveg** [comment]
It seems to happen for more packages then just arbor, sorry!

**Comment by Helveg** [comment]
So to others that upgrade their Ubuntu and hit this error: reinstall your Python binaries :)
