### ISSUE TITLE
`.context()` does not mention lack of MPI support

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1646]
**Describe the bug**
Currently if you build without MPI enabled and try to insert an MPI communicator into the context, an error occurs that would have you think that it is not possible to insert MPI communicators there. If you build arbor with MPI support the args fit neatly.

The error does not suggest MPI support might be missing, and the docs do not suggest that problems with the MPI arg might occur if support is missing.

```
Traceback (most recent call last):
  File "/home/robin/.pyenv/versions/arb-nrn/bin/bsb", line 33, in <module>
    sys.exit(load_entry_point('bsb', 'console_scripts', 'bsb')())
  File "/mnt/d/GIT/bsb3/bsb/cli.py", line 26, in scaffold_cli
    start_cli()
  File "/mnt/d/GIT/bsb3/bsb/cli.py", line 246, in start_cli
    scaffoldInstance.run_simulation(cl_args.simulation, quit=True)
  File "/mnt/d/GIT/bsb3/bsb/core.py", line 383, in run_simulation
    simulation, simulator = self.prepare_simulation(simulation_name)
  File "/mnt/d/GIT/bsb3/bsb/core.py", line 417, in prepare_simulation
    simulator = simulation.prepare()
  File "/mnt/d/GIT/bsb3/bsb/simulators/arbor/adapter.py", line 155, in prepare
    context = arbor.context(arbor.proc_allocation(), mpi)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. arbor._arbor.context()
    2. arbor._arbor.context(alloc: arbor._arbor.proc_allocation)
    3. arbor._arbor.context(threads: int = 1, gpu_id: object = None)

Invoked with: <arbor.proc_allocation: threads 1, gpu_id None>, <mpi4py.MPI.Intracomm object at 0x7f35f6059060>
```

**Comment by bcumming** [comment]
#1721 doesn't implement the interface change that I propose, and
I have written an example implementation, and tested it with all combinations of gpu/mpi:
```
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arbor
>>> ctx = arbor.context(threads=4, gpu_id=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Attempt to set an GPU communicator but Arbor is not configured with GPU support.
>>> ctx = arbor.context(threads=4, mpi=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Attempt to set an MPI communicator but Arbor is not configured with MPI support.
```
