### ISSUE TITLE
Fails to install GitHub repository via pip

### ISSUE THREAD

**Issue by lungsi** [arbor-sim/arbor#1844]
**Describe the bug**

```
# pip install git+https://github.com/arbor-sim/arbor.git
Collecting git+https://github.com/arbor-sim/arbor.git
  Cloning https://github.com/arbor-sim/arbor.git to /tmp/pip-req-build-98vu19ni
  Running command git clone --filter=blob:none --quiet https://github.com/arbor-sim/arbor.git /tmp/pip-req-build-98vu19ni
  Resolved https://github.com/arbor-sim/arbor.git to commit b8ebd7fe7c9d9fca79d6c368a0a2ecec46a343d6
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-98vu19ni/setup.py", line 3, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
#
```

**Context**

Python 3.8.2 and pip and setuptools have been upgraded
```
# pip list
Package              Version
-------------------- --------
pip                  22.0.3
setuptools           60.9.3
```

**Comment by lungsi** [comment]
**Describe the bug**

```
# pip install git+https://github.com/arbor-sim/arbor.git
Collecting git+https://github.com/arbor-sim/arbor.git
  Cloning https://github.com/arbor-sim/arbor.git to /tmp/pip-req-build-lqqfcfli
  Running command git clone --filter=blob:none --quiet https://github.com/arbor-sim/arbor.git /tmp/pip-req-build-lqqfcfli
  Resolved https://github.com/arbor-sim/arbor.git to commit b8ebd7fe7c9d9fca79d6c368a0a2ecec46a343d6
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /envs/py3-pyNNarborTest/lib/python3.8/site-packages (from arbor==0.6.1.dev0) (1.21.5)
Building wheels for collected packages: arbor
  Building wheel for arbor (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      /envs/py3-pyNNarborTest/lib/python3.8/site-packages/setuptools/dist.py:505: UserWarning: Normalizing '0.6.1-dev' to '0.6.1.dev0'
        warnings.warn(tmpl.format(**locals()))


      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-lqqfcfli/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying "Unix Makefiles" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 9.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 9.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-lqqfcfli/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Unix Makefiles" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build
        Command:
          cmake /tmp/pip-req-build-lqqfcfli -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/envs/py3-pyNNarborTest/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.2 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/resources/cmake -DARB_WITH_PYTHON=on -DPYTHON_EXECUTABLE=/envs/py3-pyNNarborTest/bin/python -DARB_WITH_MPI=False -DARB_VECTORIZE=False -DARB_ARCH=none -DARB_GPU=none -DARB_WITH_NEUROML=True -DARB_USE_BUNDLED_LIBS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is GNU 9.3.0
      -- The CXX compiler identification is GNU 9.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Could not find nvcc, please set CUDAToolkit_ROOT.
      -- Found Python3: /envs/py3-pyNNarborTest/bin/python (found suitable version "3.8.2", minimum required is "3.6.0") found components: Interpreter Development Development.Module Development.Embed
      -- PYTHON_EXECUTABLE: /envs/py3-pyNNarborTest/bin/python
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      CMake Error at /envs/py3-pyNNarborTest/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
      Call Stack (most recent call first):
        /envs/py3-pyNNarborTest/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        /envs/py3-pyNNarborTest/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindLibXml2.cmake:108 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        arborio/CMakeLists.txt:15 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 588, in setup
          env = cmkr.configure(cmake_args,
        File "/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/cmaker.py", line 289, in configure
          raise SKBuildError(

      An error occurred while configuring with CMake.
        Command:
          cmake /tmp/pip-req-build-lqqfcfli -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/envs/py3-pyNNarborTest/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.2 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/resources/cmake -DARB_WITH_PYTHON=on -DPYTHON_EXECUTABLE=/envs/py3-pyNNarborTest/bin/python -DARB_WITH_MPI=False -DARB_VECTORIZE=False -DARB_ARCH=none -DARB_GPU=none -DARB_WITH_NEUROML=True -DARB_USE_BUNDLED_LIBS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-req-build-lqqfcfli
        Working directory:
          /tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for arbor
  Running setup.py clean for arbor
Failed to build arbor
Installing collected packages: arbor
  Running setup.py install for arbor ... error
  error: subprocess-exited-with-error

  × Running setup.py install for arbor did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      /envs/py3-pyNNarborTest/lib/python3.8/site-packages/setuptools/dist.py:505: UserWarning: Normalizing '0.6.1-dev' to '0.6.1.dev0'
        warnings.warn(tmpl.format(**locals()))
      /envs/py3-pyNNarborTest/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(


      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-lqqfcfli/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying "Unix Makefiles" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 9.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 9.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-lqqfcfli/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Unix Makefiles" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build
        Command:
          cmake /tmp/pip-req-build-lqqfcfli -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/envs/py3-pyNNarborTest/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.2 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/resources/cmake -DARB_WITH_PYTHON=on -DPYTHON_EXECUTABLE=/envs/py3-pyNNarborTest/bin/python -DARB_WITH_MPI=False -DARB_VECTORIZE=False -DARB_ARCH=none -DARB_GPU=none -DARB_WITH_NEUROML=True -DARB_USE_BUNDLED_LIBS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is GNU 9.3.0
      -- The CXX compiler identification is GNU 9.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Could not find nvcc, please set CUDAToolkit_ROOT.
      -- Found Python3: /envs/py3-pyNNarborTest/bin/python (found suitable version "3.8.2", minimum required is "3.6.0") found components: Interpreter Development Development.Module Development.Embed
      -- PYTHON_EXECUTABLE: /envs/py3-pyNNarborTest/bin/python
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      CMake Error at /envs/py3-pyNNarborTest/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
      Call Stack (most recent call first):
        /envs/py3-pyNNarborTest/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        /envs/py3-pyNNarborTest/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindLibXml2.cmake:108 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        arborio/CMakeLists.txt:15 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 588, in setup
          env = cmkr.configure(cmake_args,
        File "/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/cmaker.py", line 289, in configure
          raise SKBuildError(

      An error occurred while configuring with CMake.
        Command:
          cmake /tmp/pip-req-build-lqqfcfli -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/envs/py3-pyNNarborTest/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.2 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/envs/py3-pyNNarborTest/lib/python3.8/site-packages/skbuild/resources/cmake -DARB_WITH_PYTHON=on -DPYTHON_EXECUTABLE=/envs/py3-pyNNarborTest/bin/python -DARB_WITH_MPI=False -DARB_VECTORIZE=False -DARB_ARCH=none -DARB_GPU=none -DARB_WITH_NEUROML=True -DARB_USE_BUNDLED_LIBS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-req-build-lqqfcfli
        Working directory:
          /tmp/pip-req-build-lqqfcfli/_skbuild/linux-x86_64-3.8/cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> arbor

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
#
```

**Context**

scikit-build (skbuild) and cmake is installed (`pip install scikit-build` and `pip install cmake`)
```
# pip list
Package              Version
-------------------- --------
cmake                3.22.2
scikit-build         0.13.1
```
